/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Wareki {
  eraName: string
  year: number
}
export declare function toWareki(year: number, month: number, day: number): Wareki
export declare function fromWareki(eraName: string, year: number, month: number, day: number): string
